server:
  port: 8080
spring:
  application:
    name: "ms-crediya-solicitud-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_loan_application"
    schema: "loan_application"
    username: "postgres"
    password: 12345
